# Server
server.port=8080
spring.application.name=lykup-auth-service

# PostgreSQL DB
spring.datasource.url=jdbc:postgresql://localhost:5432/lykup_auth
spring.datasource.username=postgres
spring.datasource.password=your_password_here
spring.datasource.driver-class-name=org.postgresql.Driver

# Hibernate / JPA
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=none
spring.jpa.properties.hibernate.format_sql=true

# JWT Config
jwt.secret=my_secret_key_for_lykup_auth_service
jwt.expirationMs=86400000


# Actuator (Health Check)
management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-details=always
